"""Add missing session_metadata column

Revision ID: 4dea88898882
Revises: 0001
Create Date: 2025-08-22 20:22:01.640220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dea88898882'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_metadata', sa.Text(), nullable=True, comment='Message metadata as JSON string'))
        batch_op.drop_index(batch_op.f('idx_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('idx_chat_messages_is_deleted'))
        batch_op.drop_index(batch_op.f('idx_chat_messages_message_id'))
        batch_op.drop_index(batch_op.f('idx_chat_messages_sender_type'))
        batch_op.drop_index(batch_op.f('idx_chat_messages_session_id'))
        batch_op.drop_column('metadata')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_metadata', sa.Text(), nullable=True, comment='Session metadata as JSON string'))
        batch_op.drop_index(batch_op.f('idx_chat_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('idx_chat_sessions_session_id'))
        batch_op.drop_index(batch_op.f('idx_chat_sessions_status'))
        batch_op.drop_index(batch_op.f('idx_chat_sessions_user_uuid'))
        batch_op.drop_column('metadata')

    with op.batch_alter_table('content_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_content_cache_expires_at'))
        batch_op.drop_index(batch_op.f('idx_content_cache_key_type'))
        batch_op.drop_index(batch_op.f('idx_content_cache_type_expires'))
        batch_op.create_index('idx_cache_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_cache_key_type', ['cache_key', 'cache_type'], unique=False)
        batch_op.create_index('idx_cache_type_expires', ['cache_type', 'expires_at'], unique=False)

    with op.batch_alter_table('fortune_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fortune_sessions_cached_until'))
        batch_op.drop_index(batch_op.f('idx_fortune_sessions_created_at'))
        batch_op.drop_index(batch_op.f('idx_fortune_sessions_fortune_id'))
        batch_op.drop_index(batch_op.f('idx_fortune_sessions_fortune_type'))
        batch_op.drop_index(batch_op.f('idx_fortune_sessions_session_id'))
        batch_op.drop_index(batch_op.f('idx_fortune_sessions_user_uuid'))

    with op.batch_alter_table('live2d_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_live2d_models_is_active'))
        batch_op.drop_index(batch_op.f('idx_live2d_models_model_name'))

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_system_settings_is_public'))
        batch_op.drop_index(batch_op.f('idx_system_settings_setting_key'))
        batch_op.create_index('idx_setting_key', ['setting_key'], unique=False)
        batch_op.create_index('idx_setting_public', ['is_public'], unique=False)

    with op.batch_alter_table('tarot_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tarot_cards_card_name'))
        batch_op.drop_index(batch_op.f('idx_tarot_cards_suit'))

    with op.batch_alter_table('user_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_analytics_created_at'))
        batch_op.drop_index(batch_op.f('idx_user_analytics_event_date'))
        batch_op.drop_index(batch_op.f('idx_user_analytics_event_type'))
        batch_op.drop_index(batch_op.f('idx_user_analytics_session_id'))
        batch_op.drop_index(batch_op.f('idx_user_analytics_user_uuid'))
        batch_op.create_index('idx_analytics_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_analytics_event_date', ['event_type', 'created_at'], unique=False)
        batch_op.create_index('idx_analytics_event_type', ['event_type'], unique=False)
        batch_op.create_index('idx_analytics_session_id', ['session_id'], unique=False)
        batch_op.create_index('idx_analytics_user_uuid', ['user_uuid'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_birth_date'))
        batch_op.drop_index(batch_op.f('idx_users_is_active'))
        batch_op.drop_index(batch_op.f('idx_users_is_deleted'))
        batch_op.drop_index(batch_op.f('idx_users_last_active'))
        batch_op.drop_index(batch_op.f('idx_users_uuid'))
        batch_op.drop_index(batch_op.f('idx_users_zodiac'))

    with op.batch_alter_table('zodiac_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_zodiac_info_element'))
        batch_op.drop_index(batch_op.f('idx_zodiac_info_sign'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zodiac_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_zodiac_info_sign'), ['sign'], unique=False)
        batch_op.create_index(batch_op.f('idx_zodiac_info_element'), ['element'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_zodiac'), ['zodiac_sign'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_last_active'), ['last_active_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_birth_date'), ['birth_date'], unique=False)

    with op.batch_alter_table('user_analytics', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_user_uuid')
        batch_op.drop_index('idx_analytics_session_id')
        batch_op.drop_index('idx_analytics_event_type')
        batch_op.drop_index('idx_analytics_event_date')
        batch_op.drop_index('idx_analytics_created_at')
        batch_op.create_index(batch_op.f('idx_user_analytics_user_uuid'), ['user_uuid'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_analytics_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_analytics_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_analytics_event_date'), ['event_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_analytics_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('tarot_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tarot_cards_suit'), ['suit'], unique=False)
        batch_op.create_index(batch_op.f('idx_tarot_cards_card_name'), ['card_name'], unique=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index('idx_setting_public')
        batch_op.drop_index('idx_setting_key')
        batch_op.create_index(batch_op.f('idx_system_settings_setting_key'), ['setting_key'], unique=False)
        batch_op.create_index(batch_op.f('idx_system_settings_is_public'), ['is_public'], unique=False)

    with op.batch_alter_table('live2d_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_live2d_models_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_live2d_models_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('fortune_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fortune_sessions_user_uuid'), ['user_uuid'], unique=False)
        batch_op.create_index(batch_op.f('idx_fortune_sessions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fortune_sessions_fortune_type'), ['fortune_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_fortune_sessions_fortune_id'), ['fortune_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fortune_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_fortune_sessions_cached_until'), ['cached_until'], unique=False)

    with op.batch_alter_table('content_cache', schema=None) as batch_op:
        batch_op.drop_index('idx_cache_type_expires')
        batch_op.drop_index('idx_cache_key_type')
        batch_op.drop_index('idx_cache_expires_at')
        batch_op.create_index(batch_op.f('idx_content_cache_type_expires'), ['cache_type', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_content_cache_key_type'), ['cache_key', 'cache_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_content_cache_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', sa.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('idx_chat_sessions_user_uuid'), ['user_uuid'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_sessions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.drop_column('session_metadata')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', sa.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('idx_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_messages_sender_type'), ['sender_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_messages_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('message_metadata')

    # ### end Alembic commands ###