"""Add is_active to ChatSession

Revision ID: 71a95b2551bd
Revises: 4dea88898882
Create Date: 2025-08-22 20:39:05.909278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a95b2551bd'
down_revision: Union[str, None] = '4dea88898882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###